# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
filter = { only_tables = ["vocabulary"] }
file = "src/database/schema.rs"

[migrations_directory]
dir = "src/database/migrations"
